--<ScriptOptions statementTerminator=";"/>

CREATE TABLE HUK0320.KT_DEMOTAB (
		EMP_NUM CHAR(5) NOT NULL,
		WAGE_TYPE CHAR(1),
		REGION SMALLINT,
		FIRST_LAST_NAME VARCHAR(15),
		STREET_ADDR VARCHAR(15),
		CITY VARCHAR(8),
		STATE CHAR(2),
		ZIP CHAR(6),
		HIREDATE CHAR(6),
		HOURS DECIMAL(2 , 0),
		RATE DECIMAL(6 , 2),
		WAGES DECIMAL(6 , 2),
		OVERTIME DECIMAL(6 , 2),
		COMM DECIMAL(6 , 2)
	);

